version: "3.8"
services:
  pm_task_management:
    build: .
    ports:
      - "8084:8080"
    depends_on:
      - pm_task_management_db
    env_file:
      - .env

  pm_task_management_db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5